# permissions for end users to view nodemaintenances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodemaintenance-viewer-role
rules:
- apiGroups:
  - edge.harmonycloud.cn
  resources:
  - nodemaintenances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edge.harmonycloud.cn
  resources:
  - nodemaintenances/status
  verbs:
  - get
